### ISSUE TITLE
Server fails to start (or crashes - not owner) 1.16.4 - 1.2.1

### ISSUE THREAD

**Issue by koalalord9999** [MelanX/ToolSwap#10]
When loaded on a server, it will not start up (or it crashes on startup, I'm not sure -- I'll try to get logs if there are any)

**Comment by MelanX** [comment]
Yes it crashes because it shouldn't be on server. I could change it if you want.

**Comment by koalalord9999** [comment]
Would it be hard to add so that is basically doesn't do anything if loaded onto the server? If so - that would be nice ;) The only mod left in my pack that causes teh server to have the FML X saying modlist isnt an exact match

**Comment by MelanX** [comment]
No, ToolSwap doesn't cause the red X, that is fixed. You can remove the mod on server and there is no red X :) I still can change it that the server will not crash if it's loaded.

**Comment by koalalord9999** [comment]
Thank you
