### ISSUE TITLE
Preferred Tool for specific Blocks

### ISSUE THREAD

**Issue by jankornfeld** [MelanX/ToolSwap#11]
Would be a nice feature if you could select in a menu which block you want to mine with which tool.
Like... I have an Iron Pickaxe and a Diamond Pickaxe but when I'm mining i only want the stone to be mined with the iron pickaxe and not the diamond pickaxe.

**Comment by MelanX** [comment]
You could use the config for that. Let them sort for the worst possible item. Is that good enough?
