### ISSUE TITLE
Problem with glass

### ISSUE THREAD

**Issue by V1K1NGbg** [MelanX/ToolSwap#20]
the problem is that if you have a silk touch pickaxe and you try to mine glass, it switches to an empty slot (or with a block/item) and I can't manage to fix it.

Does anyone know why is that and how I can fix it?

**Comment by MelanX** [comment]
There is a key (default G) where you can disable the switch. I can only provide this as a solution, I don’t know how this could be improved in code.

**Comment by V1K1NGbg** [comment]
I think you can make a list of items that drop with silk touch and if the block that the player is breaking is in that list and there is a silk touch enchant on the default tool, to switch to it.

that will also help for grass and not dirt and many others.

and you can also make it an option in the config.


Just a suggestion. :)
