### ISSUE TITLE
It not swap to pickaxe mine obsidian block it just change to hand when i trying to mine it

### ISSUE THREAD

**Issue by Friendclubattle78** [MelanX/ToolSwap#25]

**Comment by MelanX** [comment]
Can the pickaxe mine the obsidian? (Diamond or higher)

**Comment by Friendclubattle78** [comment]
I used Diamond Pickaxe but it cant mine obsidian it alway swap to hand

**Comment by MelanX** [comment]
For now, press shift or disable the toggle temporarily. I will try that later.

**Comment by Friendclubattle78** [comment]
Thx for fixing :D
