### ISSUE TITLE
Tools not swapping

### ISSUE THREAD

**Issue by lHemlocKl** [MelanX/ToolSwap#26]
I am running the latest forge 1.18.1-39.0.14

I have multiple pickaxes in my hotbar and it is not swapping them. When they get to 1 durability it does put it into my inventory though.

**Comment by MelanX** [comment]
You can turn this off in the config.

**Comment by lHemlocKl** [comment]
How would I get to the config?

**Comment by MelanX** [comment]
In your Minecraft folder is a folder with "config" and there is a file containing "toolswap"
