### ISSUE TITLE
Use shears for leaves if no hoe is available

### ISSUE THREAD

**Issue by s4sutler100** [MelanX/ToolSwap#30]
Does not switch to shears when placed in front of leaves

**Comment by MelanX** [comment]
The reason: an hoe is the effective tool for leaves.

**Comment by s4sutler100** [comment]
i'm using 40.0.6 today and noticed this mod stopped working.

**Comment by MelanX** [comment]
Did you press the key to disable it temporarily?

**Comment by s4sutler100** [comment]
no i just up dated the forge 

Edit by Repo owner: removed bible phrase

On Apr 3, 2022 21:16, MelanX ***@***.***> wrote: 

Did you press the key to disable it temporarily?

**Comment by s4sutler100** [comment]
what key 


On Apr 3, 2022 21:16, MelanX ***@***.***> wrote: 

Did you press the key to disable it temporarily?

**Comment by MelanX** [comment]
Default G

**Comment by s4sutler100** [comment]
yes i was
