### ISSUE TITLE
Stop first slot swapping

### ISSUE THREAD

**Issue by mbeardwell** [MelanX/ToolSwap#31]
When I scroll to another item slot it automatically switches to the first slot. I can't use any of the other item slots with tool swapping turned on which makes building impossible.

**Comment by MelanX** [comment]
Can you show me an image of your hotbar and provide information about the versions you're using? 
Forge and tool swap.

**Comment by mbeardwell** [comment]
![image](https://user-images.githubusercontent.com/17803499/162452399-7e7de15d-ef22-4a94-b1dc-2026e047cac6.png)
ToolSwap is 1.18.2-3.1.0
Forge is 40.0.24

**Comment by mbeardwell** [comment]
I've been struggling to recreate it but when it happens I have various things in the first slot and sometimes it's empty.

**Comment by MelanX** [comment]
I can't reproduce this behaviour. Do you have other mods installed?

**Comment by mbeardwell** [comment]
I do. Minecolonies, computercraft and just enough items. There are also some dependencies and 'better fps'.

`<HTML>
<HEAD>
	
	<META HTTP-EQUIV="CONTENT-TYPE" CONTENT="text/html; charset=utf-8">
	<TITLE></TITLE>
	<META NAME="GENERATOR" CONTENT="OpenOffice 4.1.12  (Win32)">
	<STYLE>
		
	</STYLE>
	
</HEAD>

<BODY TEXT="#000000">
<TABLE FRAME=VOID CELLSPACING=0 COLS=3 RULES=NONE BORDER=0>
	<COLGROUP><COL WIDTH=232><COL WIDTH=109><COL WIDTH=348></COLGROUP>
	<TBODY>
		<TR>
			<TD WIDTH=232 HEIGHT=18 ALIGN=LEFT>Better Fps - Render Distance[Forge]</TD>
			<TD WIDTH=109 ALIGN=LEFT>someaddon</TD>
			<TD WIDTH=348 ALIGN=LEFT>1.18.1-1.4</TD>
		</TR>
		<TR>
			<TD HEIGHT=18 ALIGN=LEFT>CC: Tweaked</TD>
			<TD ALIGN=LEFT>SquidDev</TD>
			<TD ALIGN=LEFT>1.18.2-1.100.4</TD>
		</TR>
		<TR>
			<TD HEIGHT=18 ALIGN=LEFT>Domum Ornamentum</TD>
			<TD ALIGN=LEFT>OrionOnline</TD>
			<TD ALIGN=LEFT>1.18.2-1.0.48-ALPHA-universal</TD>
		</TR>
		<TR>
			<TD HEIGHT=18 ALIGN=LEFT>Inventory Profiles Next</TD>
			<TD ALIGN=LEFT>mirinimi</TD>
			<TD ALIGN=LEFT>forge-1.18.2-1.3.5</TD>
		</TR>
		<TR>
			<TD HEIGHT=17 ALIGN=LEFT>Just Enough Resources (JER)</TD>
			<TD ALIGN=LEFT>way2muchnoise</TD>
			<TD ALIGN=LEFT>1.18.2-0.14.1.164</TD>
		</TR>
		<TR>
			<TD HEIGHT=18 ALIGN=LEFT>MineColonies</TD>
			<TD ALIGN=LEFT>H3lay</TD>
			<TD ALIGN=LEFT>1.18.2-1.0.568-BETA</TD>
		</TR>
		<TR>
			<TD HEIGHT=17 ALIGN=LEFT>Multi-Piston</TD>
			<TD ALIGN=LEFT>H3lay</TD>
			<TD ALIGN=LEFT>1.18.2-1.2.3-ALPHA</TD>
		</TR>
		<TR>
			<TD HEIGHT=18 ALIGN=LEFT>Structurize</TD>
			<TD ALIGN=LEFT>H3lay</TD>
			<TD ALIGN=LEFT>1.18.2-1.0.370-ALPHA</TD>
		</TR>
		<TR>
			<TD HEIGHT=18 ALIGN=LEFT>Xaero's Minimap</TD>
			<TD ALIGN=LEFT>xaero96</TD>
			<TD ALIGN=LEFT>forge_1.18.2_22.4.0</TD>
		</TR>
		<TR>
			<TD HEIGHT=18 ALIGN=LEFT>Xaero's World Map</TD>
			<TD ALIGN=LEFT>xaero96</TD>
			<TD ALIGN=LEFT>forge_1.18.2_1.20.6</TD>
		</TR>
		<TR>
			<TD HEIGHT=18 ALIGN=LEFT>Automatic Tool Swap</TD>
			<TD ALIGN=LEFT>MelanX</TD>
			<TD ALIGN=LEFT>1.18.2-3.1.0</TD>
		</TR>
		<TR>
			<TD HEIGHT=18 ALIGN=LEFT>BlockUI</TD>
			<TD ALIGN=LEFT>H3lay</TD>
			<TD ALIGN=LEFT>1.18.2-0.0.47-ALPHA</TD>
		</TR>
		<TR>
			<TD HEIGHT=18 ALIGN=LEFT>Just Enough Items (JEI)</TD>
			<TD ALIGN=LEFT>mezz</TD>
			<TD ALIGN=LEFT>1.18.2-9.5.5.174</TD>
		</TR>
	</TBODY>
</TABLE>
</BODY>

</HTML>
`

**Comment by MelanX** [comment]
Sorry, I still can't reproduce this. Maybe it helps to turn off the toggle state by using the keybind.
