### ISSUE TITLE
1.19 not working

### ISSUE THREAD

**Issue by GHOSTKING13** [MelanX/ToolSwap#34]
After I install it, I can't switch between single player and server. I use the latest FORGE and MOD, or I still need anything?

**Comment by MelanX** [comment]
Only Forge and this mod or other mods as well?
Back in the days, I heard that someone had problems with a mod and this tool switch mod. Maybe it’s still/again the case.

**Comment by blank826** [comment]
not work in 1.19.only forge and this mod.

**Comment by MelanX** [comment]
Which versions? Forge and this mod

**Comment by blank826** [comment]
> Which versions? Forge and this mod

1.19-Forge_41.0.91   ,ToolSwap-1.19-4.1.4

**Comment by MelanX** [comment]
I think it needs a bit more time to fix this since it works in dev environment. That is really weird, maybe I find some time for that on weekend.

**Comment by tibtiq** [comment]
I'm having issues with the mod aswell. Seemingly the only time the mod works is with swords against web blocks. Additionally when having both a sword and shears in the hotbar the mod chooses the sword.

Mincraft: 1.19

Mods installed
- Forge 41.0.98
- ToolSwap 1.19-4.1.5

**Comment by MelanX** [comment]
Set `ignore_harvest_level` to false in config for now. This fixes the behavior temporarily.

**Comment by tibtiq** [comment]
> Set `ignore_harvest_level` to false in config for now. This fixes the behavior temporarily.

Thanks, doing this does allow the mod to work.
