### ISSUE TITLE
ToolSwap doesn't work when a tool is already selected (default config settings)

### ISSUE THREAD

**Issue by tibtiq** [MelanX/ToolSwap#37]
![image](https://user-images.githubusercontent.com/29826331/179430355-b4f24508-833d-4f00-a6bc-59b966698d67.png)
As shown above when I have he axe selected and try digging the dirt, ToolSwap doesn't do anything. The only time ToolSwap will work when a tool is already selected is against cobwebs. I've been able to narrow it down to the `ignore_harvest_level` setting in the config being set to true. By default the setting is set to true. Setting it to false makes the mod work as expected.

Based on the description given in the config I'm not sure why this setting exists or why the default value for it is true.

Mincraft: 1.19

Mods installed
- Forge 41.0.98
- ToolSwap 1.19-4.1.6

**Comment by MelanX** [comment]
Sorry that it's not available on CurseForge yet. My build server has some problems. I hope that it's being fixed over night without my help because it just happened without any change. If it's not fixed tomorrow, I'll try to find a solution for that.
