### ISSUE TITLE
swap tools

### ISSUE THREAD

**Issue by ben5446** [MelanX/ToolSwap#38]
its not swapping im using nerthite tools as a test
i also used diamonds still not working

im using forge 1.19 with toolswap 1.19

**Comment by MelanX** [comment]
Which versions exactly?

**Comment by ben5446** [comment]
toolswap 1.19-4.1.7
forge 1.19-forge-41.0.100

**Comment by MelanX** [comment]
Just to make sure that it’s the mod because there already were other users where that was the problem: did you accidentally disable the swapping? (Default keybind G)
If not, I will look at the problem later today

**Comment by ben5446** [comment]
sorry i didn't have time to check earlier ill check rn
