### ISSUE TITLE
swap does not work

### ISSUE THREAD

**Issue by MarlonPra** [MelanX/ToolSwap#39]
I use ToolSwap-1.18.2-3.1.4 version and the mod doesn't work, I don't know why, it doesn't change or anything.

https://user-images.githubusercontent.com/79668146/180356961-4d4a3524-a845-4a83-be33-da294b6e77c4.mp4

**Comment by MelanX** [comment]
Did you change the config? If yes, please tell me your settings.

**Comment by MarlonPra** [comment]
> Did you change the config? If yes, please tell me your settings.

nope, I didn't change anything in the configuration, I just put it in and that's all.
![image](https://user-images.githubusercontent.com/79668146/180366442-4ae0a844-f01a-47c2-8c29-913cc8a0b915.png)

**Comment by MelanX** [comment]
Forgot to fix these things in the 1.18 version of the mod, thank you :)
