### ISSUE TITLE
Compatibility Check

### ISSUE THREAD

**Issue by nanohard** [MelanX/ToolSwap#4]
Client checks to see if this mod is on the server and complains if it isn't, leading to a false positive of incompatibility.
If it is installed on the server, the server crashes, obviously.

Error on client
```
[06Dec2020 10:38:04.232] [Netty Client IO #0/INFO] [net.minecraftforge.fml.client.ClientHooks/CLIENTHOOKS]: Client has mods that are missing on server: [toolswap]
```

**Comment by MelanX** [comment]
You should still be able to join if this mod is loaded in client.
Is this issue only related to the X and checkmark in the servers screen?

**Comment by nanohard** [comment]
Yeah, it's not a usability issue; can still join the server. But end users don't know this and often won't try when they see the red X. I just opened the issue to make you aware. Not sure if there's a way to tell the server, "Hey! This a client-side only mod. Nothing out of order here, officer."

**Comment by MelanX** [comment]
Alright, I'm trying to find a solution for this!

**Comment by nanohard** [comment]
Here we go!
[https://mcforge.readthedocs.io/en/latest/concepts/sides/#writing-one-sided-mods](https://mcforge.readthedocs.io/en/latest/concepts/sides/#writing-one-sided-mods)
