### ISSUE TITLE
Not available

### ISSUE THREAD

**Issue by Looodon** [MelanX/ToolSwap#41]
Hey, the mod is available on the web version of curseforge, but not the app for some reason so I can't add it to my mod list through the app. Will the game version categorization (on the website) be updated from 1.16.5 to 1.19.2 any time soon? idk if that might fix it. Thanks!

**Comment by MelanX** [comment]
![image](https://user-images.githubusercontent.com/26039509/192323031-9fd14925-d5f5-4929-8af7-f3c9cbe1d883.png)
Was searching for "Tool Swap" on 1.19.2 profile

**Comment by Looodon** [comment]
it didn't show up yesterday, but i just checked and it appears now idk how lol thanks for your time!
