### ISSUE TITLE
Pick doesn't get swapped to when glass is targeted.

### ISSUE THREAD

**Issue by sowby911** [MelanX/ToolSwap#45]
### Minecraft version

1.19.4

### ToolSwap version

4.4.1

### Forge version

45.0.23

### The latest.log file

None. I'm the worst.

### Issue description

Pick doesn't get swapped to when glass is targeted.

### Steps to reproduce

Get pickaxe in hot bar slot 1.
Go to hand in hot bar slot 2.
Ensure that Tool Swap is on.
Left click on glass.

**Comment by MelanX** [comment]
That's the case because vanilla doesn't add glass to the tag which specifies which tool should be used to mine a block. There's no tool specified for glass. If you own the server, or play in single player, you could simply add glass to this block tag: `minecraft:mineable/pickaxe`.
