### ISSUE TITLE
Crash when trying to swap to the correct breaking tool.

### ISSUE THREAD

**Issue by Baenjamin** [MelanX/ToolSwap#49]
### Minecraft version

1.20.1

### ToolSwap version

1.20.1-5.0.2

### Forge version

47.2.21

### The latest.log file

https://gist.github.com/Baenjamin/2d4bdcddb6829c16e79905b0a675203b

### Issue description

Crash when automatically switching to the correct tool when breaking a flower from Ars Nouveau. Happened during a playthrough of my modpack, when just updating from 5.0.1 to 5.0.2. It did not happen prior to the update.

### Other information

Crash report:
[crash-2024-03-31_16.16.23-client.txt](https://github.com/MelanX/ToolSwap/files/14816297/crash-2024-03-31_16.16.23-client.txt)

**Comment by MelanX** [comment]
Thank you! I didn't run into that problem since I only tried with vanilla tools, and similar tools. For now, just use the older version, I marked 5.0.2 as alpha. That way, most users shouldn't download it, I hope.

**Comment by MelanX** [comment]
Please test if 5.0.3 fixes your problem!
CurseForge: https://legacy.curseforge.com/minecraft/mc-mods/automatic-tool-swap/files/5224902
Modrinth: https://modrinth.com/mod/automatic-tool-swap/version/1.20.1-5.0.3

**Comment by Baenjamin** [comment]
I shall try B) But i did have iron shovel, pickaxe, sword and axe in my inventory. And it looked like it tried to switch to shovel when i tried to break a modded flower that had spawned in the wild. 

I'll edit this comment once I've tested the same thing that i did earlier when i crashed.

Edit: Took me forever to find the same block that i crashed on. But in the end i did find it. And the tools didn't switch oddly around, so no crash with the new version at least. B) Cheers !

**Comment by MelanX** [comment]
Thanks for your feedback!
