### ISSUE TITLE
Silent Gear Tools not swapping?

### ISSUE THREAD

**Issue by WimpieRatte** [MelanX/ToolSwap#50]
### Minecraft version

1.20.1

### ToolSwap version

1.20.1-5.0.4

### Forge version

47.2.20

### The latest.log file

https://pastebin.com/mGHmBeXX

### Issue description

Using latest version of Silent Gear (1.20.1-3.6.3) & Silent Lib (1.20.1-8.0.0).
None of the tools for Silent Gear are being swapped to automatically.

I attached my latest log file, but I only had EMI, Silent Gear, Silent Lib and ToolSwap installed, so easy to recreate.

### Steps to reproduce

1. Install  Silent Gear, Silent Lib and ToolSwap
2. Craft Silent Gear tools
3. Try to mine something where it should switch. (e.g: Stone or Wood)

**Comment by MelanX** [comment]
If you’re able to add a datapack on your instance, you could create one to include the wrong tags to the correct tags. More information about this problem here: https://github.com/SilentChaos512/Silent-Gear/issues/663
This isn’t my fault but a problem that Silent Gear uses the wrong item tags.

**Comment by WimpieRatte** [comment]
Thank you!
Also, thank you for logging a ticket for this with Silent Gear!

**Comment by WimpieRatte** [comment]
@MelanX: So I managed to fix this for all the below mentioned tools, except for the Machete.
Could you please advise me why the Machete is not working with the tags I gave it?
(Are you avoiding the tool switch when the tool also contains tags with something like sword?)

(I installed CraftTweaker, created a new scripts/custom.zs file and added the following code in the file:)

`//adding default minecraft tags to some silent gear tools/weapons:
<tag:items:minecraft:tools>.add(<item:silentgear:paxel>);
<tag:items:minecraft:pickaxes>.add(<item:silentgear:paxel>);
<tag:items:minecraft:shovels>.add(<item:silentgear:paxel>);
<tag:items:minecraft:axes>.add(<item:silentgear:paxel>);
<tag:items:forge:tools>.add(<item:silentgear:paxel>);
<tag:items:forge:tools/pickaxes>.add(<item:silentgear:paxel>);
<tag:items:forge:tools/shovels>.add(<item:silentgear:paxel>);
<tag:items:forge:tools/axes>.add(<item:silentgear:paxel>);

<tag:items:minecraft:tools>.add(<item:silentgear:mattock>);
<tag:items:minecraft:hoes>.add(<item:silentgear:mattock>);
<tag:items:minecraft:shovels>.add(<item:silentgear:mattock>);
<tag:items:minecraft:axes>.add(<item:silentgear:mattock>);
<tag:items:forge:tools>.add(<item:silentgear:mattock>);
<tag:items:forge:tools/hoes>.add(<item:silentgear:mattock>);
<tag:items:forge:tools/shovels>.add(<item:silentgear:mattock>);
<tag:items:forge:tools/axes>.add(<item:silentgear:mattock>);

**<tag:items:minecraft:tools>.add(<item:silentgear:machete>);
<tag:items:minecraft:axes>.add(<item:silentgear:machete>);
<tag:items:forge:tools>.add(<item:silentgear:machete>);
<tag:items:forge:tools/axes>.add(<item:silentgear:machete>);**

<tag:items:minecraft:tools>.add(<item:silentgear:axe>);
<tag:items:minecraft:axes>.add(<item:silentgear:axe>);
<tag:items:forge:tools>.add(<item:silentgear:axe>);
<tag:items:forge:tools/axes>.add(<item:silentgear:axe>);

<tag:items:minecraft:tools>.add(<item:silentgear:pickaxe>);
<tag:items:minecraft:pickaxes>.add(<item:silentgear:pickaxe>);
<tag:items:forge:tools>.add(<item:silentgear:pickaxe>);
<tag:items:forge:tools/pickaxes>.add(<item:silentgear:pickaxe>);

<tag:items:minecraft:tools>.add(<item:silentgear:shovel>);
<tag:items:minecraft:shovels>.add(<item:silentgear:shovel>);
<tag:items:forge:tools>.add(<item:silentgear:shovel>);
<tag:items:forge:tools/shovels>.add(<item:silentgear:shovel>);

<tag:items:minecraft:tools>.add(<item:silentgear:hoe>);
<tag:items:minecraft:hoes>.add(<item:silentgear:hoe>);
<tag:items:forge:tools>.add(<item:silentgear:hoe>);
<tag:items:forge:tools/hoes>.add(<item:silentgear:hoe>);`

**Comment by MelanX** [comment]
Fixed in 5.0.5!

**Comment by WimpieRatte** [comment]
Dude, thank you so much for how you respond to these!
Updating my pack immediately!
