### ISSUE TITLE
Not working on certain server

### ISSUE THREAD

**Issue by wolfcharm** [MelanX/ToolSwap#51]
### Minecraft version

1.20.1

### ToolSwap version

1.20.1-5.0.4

### Forge version

47.2.0

### The latest.log file

https://gist.github.com/wolfcharm/8104fc60fafd48cdc611f344733f2c9d

### Issue description

On skyblock.net server ToolSwap not working at all.

### Steps to reproduce

1. Connect skyblock.net server
2. Create your island
3. Try braking blocks

**Comment by MelanX** [comment]
The problem is that the server is still on 1.19.2, and in this version, there are no item tags for shovels, hoes, pickaxes, and axes. Automatic Tool Swap 1.20+ uses these tool tags.
I added a config for 1.20.1 but can't release it at the moment. You could try playing with 1.19.2 tool swap.
