### ISSUE TITLE
Crystal Tools tools not swapping - even with correct tags

### ISSUE THREAD

**Issue by WimpieRatte** [MelanX/ToolSwap#52]
### Minecraft version

1.20.1

### ToolSwap version

1.20.1-5.0.4

### Forge version

47.2.30

### The latest.log file

N/A

### Issue description

Here's a screenshot (with F3 + H details included) to show that I did add the correct tags (worked for other mods like Mekanism tools, Piercing paxels and Silent Gear), but the Crystal Tools tools still does not want to switch:
![grafik](https://github.com/MelanX/ToolSwap/assets/42098550/7d41a44a-3aa6-4875-9bac-98bb2a29ddce)

Any idea why?

### Steps to reproduce

1. Install Crystal Tools and Automatic Toolswap mods.
2. Add tags to Crystal Tools tools via an app like CraftTweaker
3. Try use any of the crystal tools to see if it allows you to switch.

### Other information

.zs file (for CraftTweaker) adds the tags as follows:

<tag:items:minecraft:tools>.add(<item:crystal_tools:crystal_axe>, <item:crystal_tools:crystal_pickaxe>, <item:crystal_tools:crystal_shovel>, <item:crystal_tools:crystal_hoe>, <item:crystal_tools:crystal_aiot>);
<tag:items:minecraft:axes>.add(<item:crystal_tools:crystal_axe>, <item:crystal_tools:crystal_aiot>);
<tag:items:minecraft:pickaxes>.add(<item:crystal_tools:crystal_pickaxe>, <item:crystal_tools:crystal_aiot>);
<tag:items:minecraft:shovels>.add(<item:crystal_tools:crystal_shovel>, <item:crystal_tools:crystal_aiot>);
<tag:items:minecraft:hoes>.add(<item:crystal_tools:crystal_hoe>, <item:crystal_tools:crystal_aiot>);

**Comment by MelanX** [comment]
This happens because the tools aren't registered as `DiggerItem` (a vanilla class). Without this, I can't get the tool tier. Without the tier, I can't check if it's the correct tool to drop an item. Because of that, it'll be skipped. I need to add something to make these items compatible.

**Comment by WimpieRatte** [comment]
Is this something I can log on his side as an enhancement request?

**Comment by MelanX** [comment]
When working on the other issue, I saw that it only needs to extend `TieredItem` which is a pretty basic class. The author should be able to extend this class easily.
You don't need to do anything, I'll try to create a pull request for that. If I can't do it (whyever, I don't know), I'll create an issue.

**Comment by MelanX** [comment]
When will-y merges that pull request, this issue here can be closed.

**Comment by WimpieRatte** [comment]
Thanks a LOT! :D

**Comment by will-y** [comment]
Merged and new release uploaded 1.20.1-1.5.3. Available on Modrinth and Github right now and then on Curse whenever they approve it

**Comment by WimpieRatte** [comment]
Testing it now - but I think it's crashing.
When I reverted to 1.5.2, it didn't crash.
Log attached.
[crash-2024-05-18_01.42.41-client.txt](https://github.com/MelanX/ToolSwap/files/15358845/crash-2024-05-18_01.42.41-client.txt)

**Comment by will-y** [comment]
Weird, didn't happen in my dev environment. Uploaded a new build with the same version number

**Comment by WimpieRatte** [comment]
Legend! Thanks!
Tested successfully! :D
Also toolswaps nicely now when i add the tags.
