### ISSUE TITLE
Lost compatibility

### ISSUE THREAD

**Issue by chriskeena** [MelanX/ToolSwap#53]
### Minecraft version

1.20.1

### ToolSwap version

5.0.5

### Forge version

Neoforge 47.1.105

### The latest.log file

N/A

### Issue description

The latest patch of Toolswap has caused it to cease recognising blocks added by Minecolonies and Domum Ornamentum.

**Comment by MelanX** [comment]
You mean that it works in 5.0.4 and in 5.0.5, it doesn’t work anymore?

**Comment by chriskeena** [comment]
> You mean that it works in 5.0.4 and in 5.0.5, it doesn’t work anymore?

You are correct. Further testing showed that even vanilla tools weren't being selected for vanilla blocks. Reverting to 5.0.4 was my answer.

**Comment by MelanX** [comment]
Uploading a 5.0.6 now. No changes on GitHub, but I had some stuff locally in datapacks and currently, I'm building and publishing my mods on my computer and didn't thing about removing this for building. Yeah, accidentally published a broken datapack with that version.
Sorry for that and thanks!
