### ISSUE TITLE
Curseforge Wrong Version

### ISSUE THREAD

**Issue by Camryn-The-Eevee** [MelanX/ToolSwap#54]
### Minecraft version

1.20.1

### ToolSwap version

5.0.4

### Forge version

1.253.0

### The latest.log file

https://pastebin.com/b0TQ4j55

### Issue description

Curseforge lists Toolswap as being for V1.20.6, but it is in fact, not.
![image_2024-06-02_204120323](https://github.com/MelanX/ToolSwap/assets/126028294/7d45f4e4-ffc7-4840-92ae-00ce5ca97b85)

### Steps to reproduce

1. Install Automatic Toolswap on a 1.20.6 modpack
2. Run modpack

**Comment by MelanX** [comment]
So, you mean that it doesn’t work? It crashes?

PS: the issue template you just filled out has a link with explanation how to get the log. https://git.io/mclogs
