### ISSUE TITLE
Broken tool doesn't disappear

### ISSUE THREAD

**Issue by GoblinFace** [MelanX/ToolSwap#8]
When my tool runs out of durability, it will not break. Once it has got no durability left, it flashes but does not break.

https://user-images.githubusercontent.com/76542687/103051396-a560d480-45d1-11eb-8e0a-af4d8d74e83c.mp4

**Comment by MelanX** [comment]
What was you doing? Breaking or right clicking?
On server or client?
Which config do you have?

**Comment by noobimpostor** [comment]
1 tool health is left,  then swaptool doesn't allow to use it

**Comment by MelanX** [comment]
> 1 tool health is left, then swaptool doesn't allow to use it

That is intended and can be disabled in config.

**Comment by noobimpostor** [comment]
But its cool for afk , i m doing afk on mobile with swaptool

**Comment by MelanX** [comment]
Turn it off when being afk?

**Comment by noobimpostor** [comment]
No , its useful .see
(I just added blocks in my inventory that i needed)

https://user-images.githubusercontent.com/65805762/108236410-e35f1c80-716c-11eb-998d-1a346fce22e9.mp4
